apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qxslla5qz-python 
  janus-idp.io/tekton: qxslla5qz-python
  backstage.io/kubernetes-id: qxslla5qz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qxslla5qz-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml