apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qxslla5qz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qxslla5qz-python 
  name: qxslla5qz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qxslla5qz-python 
